// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFiles(arg1, arg2) {
  return window['go']['main']['App']['CopyFiles'](arg1, arg2);
}

export function GetDiff(arg1) {
  return window['go']['main']['App']['GetDiff'](arg1);
}

export function LoadComparison(arg1, arg2) {
  return window['go']['main']['App']['LoadComparison'](arg1, arg2);
}

export function LoadGitComparison(arg1, arg2) {
  return window['go']['main']['App']['LoadGitComparison'](arg1, arg2);
}

export function SaveMerge(arg1) {
  return window['go']['main']['App']['SaveMerge'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SuggestPaths(arg1) {
  return window['go']['main']['App']['SuggestPaths'](arg1);
}
