// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyFiles(arg1:Array<string>,arg2:string):Promise<string>;

export function GetDiff(arg1:string):Promise<main.DiffResult>;

export function LoadComparison(arg1:string,arg2:string):Promise<main.ComparisonResult>;

export function LoadGitComparison(arg1:string,arg2:string):Promise<main.ComparisonResult>;

export function SaveMerge(arg1:main.MergeSaveRequest):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SuggestPaths(arg1:string):Promise<Array<string>>;
